SystemOrganization addCategory: #'ElasticSearch-Core'!
SystemOrganization addCategory: #'ElasticSearch-Core-Aggregations'!
SystemOrganization addCategory: #'ElasticSearch-Core-Analyzer'!
SystemOrganization addCategory: #'ElasticSearch-Core-Filter'!
SystemOrganization addCategory: #'ElasticSearch-Core-Functions'!
SystemOrganization addCategory: #'ElasticSearch-Core-Mapping'!
SystemOrganization addCategory: #'ElasticSearch-Core-QueryDSL'!
SystemOrganization addCategory: #'ElasticSearch-Core-Search'!
